configurations:
  - sources:
      include:
        - core/Sources
    templates:
      - stencil/sourcery-template/SparkCoreAutoMockable.stencil
    output: core/Unit-tests/Sourcery/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheme]
      autoMockableTestableImports: [SparkCore]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting]
  - sources:
      include:
        - core/Sources
    templates:
      - stencil/sourcery-template/SparkCoreAutoMockTest.stencil
    output: core/Unit-tests/Sourcery/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheme]
      autoMockableTestableImports: [SparkCore]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting]
  - sources:
      include:
        - core/Sources
    templates:
      - stencil/sourcery-template/SparkCoreAutoPublisherTest.stencil
    output: core/Unit-tests/Sourcery/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheme]
      autoMockableTestableImports: [SparkCore]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting]
  - sources:
      include:
        - core/Sources
    templates:
      - stencil/sourcery-template/SparkCoreAutoViewModelStub.stencil
    output: core/Unit-tests/Sourcery/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheme]
      autoMockableTestableImports: [SparkCore]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting]



      