name: Spark
include:
  - xcodegen/spark-shared.yml
  - xcodegen/spark-core.yml
  - xcodegen/spark-core-unit-tests.yml
  - xcodegen/spark-core-snapshot-tests.yml
  - xcodegen/spark.yml

targetTemplates:
  SparkCoreSchemeTemplate:
    templates:
      - SparkCoreTemplate
    scheme:
      testTargets:
        - name: SparkCoreUnitTests
        - name: SparkCoreSnapshotTests
      gatherCoverageData: true

targets:
  SparkCore:
    templates:
      - SparkCoreSchemeTemplate
