name: Spark
configs:
  Debug: debug
  Release: release
options:
  defaultConfig: Release
  groupSortPosition: top
  deploymentTarget:
    iOS: 14.0
  useBaseInternationalization: false
  groupOrdering:
    - order: [framework, unit-tests, demo, ui-tests, resources]
targets:
  Spark:
    platform: iOS
    type: framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adevinta.spark"
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    info:
      path: framework/Info.plist
    sources:
      - path: framework
    scheme:
      testTargets:
        - name: SparkTests
      gatherCoverageData: true

  SparkTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adevinta.spark.tests"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    info:
      path: unit-tests/Info.plist
    sources:
      - path: unit-tests
    dependencies:
      - target: Spark

  SparkDemo:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adevinta.spark.demo"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    info:
      path: demo/Info.plist
    sources:
      - path: demo
    scheme:
      testTargets:
        - name: SparkDemoUITests
      language: fr
      region: FR

  SparkDemoUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: ui-tests/Info.plist
    sources:
      - path: ui-tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adevinta.spark.demo.uitests"
        TEST_TARGET_NAME: SparkDemo
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - target: SparkDemo
