# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane to generate xcodeproj with xcodegen"
  lane :generate_xcodeproj do |options|
    root_folder = options[:ROOT_FOLDER] || "."
    templateFile = options[:TEMPLATE_FILE] || ""
    sh("scripts/xcodeproj/generate.sh", root_folder, templateFile)
  end

  desc "Lane for build framework"
  lane :build_framework do |options|
    packages_path = "#{File.expand_path("..", Dir.pwd)}/packages_cache"
    gym(
      clean: true,
      scheme: options[:TARGET_NAME],
      project: "Spark.xcodeproj",
      skip_package_ipa: true,
      cloned_source_packages_path: packages_path,
      disable_package_automatic_updates: true,
      # skip_package_dependencies_resolution: ENV["HAS_PACKAGES_CACHE_HIT"],
    )
  end

  desc "Lane for unit testing"
  lane :unit_tests do |options|
    packages_path = "#{File.expand_path("..", Dir.pwd)}/packages_cache"
    scan(
      clean: true,
      # build_for_testing: true,
      scheme: options[:TARGET_NAME],
      cloned_source_packages_path: packages_path,
      disable_package_automatic_updates: true,
      # skip_package_dependencies_resolution: ENV["HAS_PACKAGES_CACHE_HIT"],
      project: "Spark.xcodeproj",
      output_directory: "out",
      result_bundle: true,
      device: "iPhone 14 Pro",
    )
  end
end
