# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do |lane, options|
    ENV["SCRIPTS_PATH"] = "../scripts/fastlane/"
  end

  desc "Lane for build framework"
  lane :build_framework do |options|
    gym(
      clean: true,
      scheme: options[:TARGET_NAME],
      project: "Spark.xcodeproj",
      skip_package_ipa: true,
    )
  end

  desc "Lane for unit testing"
  lane :unit_tests do |options|
    puts "LOGSPARK UNIT TEST P1"
    generate_sourcery_files
    puts "LOGSPARK UNIT TEST P2"
    generate_xcodeproj
    puts "LOGSPARK UNIT TEST P3"

    scan(
      clean: true,
      scheme: options[:TARGET_NAME],
      project: "Spark.xcodeproj",
      output_directory: "out",
      result_bundle: true,
      device: "iPhone 14 Pro",
    )
  end

  desc "Lane to generate xcodegen"
  lane :generate_xcodeproj do
    puts "LOGSPARK XCODEPROJ P1"
    sh(ENV["SCRIPTS_PATH"] + "generate-swiftgen.sh")
    puts "LOGSPARK XCODEPROJ P2"
  end

  desc "Lane to generate sourcery"
  lane :generate_sourcery_files do
    puts "LOGSPARK SOURCERY P1"
    sh(ENV["SCRIPTS_PATH"] + "generate-sourcery-files.sh")
    puts "LOGSPARK SOURCERY P2"
  end
end
