# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane for build framework"
  lane :build_framework do
    gym(
      clean: true,
      scheme: "Spark",
      project: "Spark.xcodeproj",
      skip_package_ipa: true,
    )
  end
  lane :unit_tests do
    scan(
      clean: true,
      scheme: "Spark",
      project: "Spark.xcodeproj",
    )
  end
  lane :ui_tests do
    scan(
      clean: true,
      scheme: "SparkDemo",
      project: "Spark.xcodeproj",
    )
  end
end
