name: build-framework
on:
  push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane build_framework
  unit_tests:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: adevinta/spark-ios-snapshots
          path: ../spark-ios-snapshots
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - name: run fastlane lane unit_tests
        run: fastlane unit_tests
      - name: Tar files
        run: tar -cvf xcresult.tar out/Spark.xcresult
        continue-on-error: true
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: xcresult
          path: xcresult.tar
          retention-days: 15
