name: build-demo
on:
  workflow_call
    
env:
  app_name: SparkDemo
  xcode_path: "/Applications/Xcode_15.4.app"

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
    - name: Select Xcode
      run: sudo xcode-select -s ${{ env.xcode_path }}
    - name: Checkout Action
      uses: actions/checkout@v4
    - name: Run xcodegen
      uses: xavierLowmiller/xcodegen-action@1.2.2
      with:
        spec: project.yml
        version: '2.41.0'
    - name: Build
      run: |
        xcodebuild -scheme ${{ env.app_name }} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro,OS=17.5' build
    - name: Upload xcresult file
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ env.app_name }}-${{ github.run_number }}.xcresult
        path: ${{ env.app_name }}.xcresult
        retention-days: 15
