name: build-framework
on:
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  core_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - name: run fastlane build_framework TARGET_NAME:SparkCore
        run: fastlane build_framework TARGET_NAME:SparkCore
  core_unit_tests:
    name: core_unit_tests
    needs: [ core_build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: run install dependencies
        run: |
          echo "LOGSPARK"
          ls
          echo "LOGSPARK 2"
          brew install sourcery
          ls
          echo "LOGSPARK 3"
          brew install swiftgen
          ls
          echo "LOGSPARK 4"

      # TODO: just for testing - to remove asap
      - name: run fastlane test_fastlane
        run: fastlane test_fastlane

      # - uses: xavierLowmiller/xcodegen-action@1.1.2
      #   with:
      #     spec: project.yml
      #     version: '2.33.0'

      - name: run fastlane unit_tests TARGET_NAME:SparkCore
        run: fastlane unit_tests TARGET_NAME:SparkCore



      - uses: actions/checkout@v3
        with:
          repository: adevinta/spark-ios-snapshots
          path: spark-ios-snapshots



      - name: Tar files
        run: tar -cvf xcresult.tar out/SparkCore.xcresult
        continue-on-error: true
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: xcresult
          path: xcresult.tar
          retention-days: 15

  build:
    needs: [ core_build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
          # TODO: not sure if we needed this run install 
      - name: run install swiftgen
        run: brew install swiftgen
      - name: run fastlane build_framework TARGET_NAME:Spark
        run: fastlane build_framework TARGET_NAME:Spark
  unit_tests:
    name: unit_tests
    needs: [ build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - name: run fastlane lane unit_tests TARGET_NAME:Spark
        run: fastlane unit_tests TARGET_NAME:Spark
      - name: Tar files
        run: tar -cvf xcresult.tar out/Spark.xcresult
        continue-on-error: true
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: xcresult
          path: xcresult.tar
          retention-days: 15
