name: build-framework
on:
  push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane build_framework
  unit_tests:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane unit_tests
      - name: Tar files
        run: tar -cvf xcresult.tar out/Spark.xcresult
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: Spark.xcresult
          path: xcresult.tar
          retention-days: 15
