name: build-framework
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  core_build:
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "build_framework"
          target: "SparkCore"

  core_unit_tests:
    name: core_unit_tests
    needs: [core_build]
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Install Sourcery
        run: brew install sourcery
      - name: Run Sourcery
        run: sourcery
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "unit_tests"
          target: "SparkCore"
      - name: Tar files
        run: tar -cvf xcresult-SparkCore.tar out/SparkCore.xcresult
        continue-on-error: true
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: xcresult-SparkCore
          path: xcresult-SparkCore.tar
          retention-days: 15

  # core_snapshot_tests:
  #   name: core_snapshot_tests
  #   needs: [core_build]
  #   runs-on: macos-13-xl
  #   steps:
  #     - name: Checkout actions
  #       uses: actions/checkout@v4
  #     - name: Install Sourcery
  #       if: steps.cache-homebrew-packages.outputs.cache-hit != 'true'
  #       run: brew install sourcery
  #     - name: Run Sourcery
  #       run: sourcery
  #     - name: Run xcodegen
  #       uses: xavierLowmiller/xcodegen-action@1.1.2
  #       with:
  #         spec: project-ci.yml
  #         version: "2.33.0"
  #     - name: Extract branch name
  #       shell: bash
  #       run: echo "branch=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
  #     - name: Run snapshots
  #       uses: actions/checkout@v4
  #       with:
  #         repository: adevinta/spark-ios-snapshots
  #         ref: ${{ env.branch }}
  #         path: spark-ios-snapshots
  #     - name: Run fastlane unit_tests TARGET_NAME:SparkDemo
  #       run: bundle exec fastlane unit_tests TARGET_NAME:SparkDemo
  #       env:
  #         HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}
  #     - name: Tar files
  #       run: tar -cvf xcresult-SparkCoreSnapshots.tar out/SparkCoreSnapshots.xcresult
  #       continue-on-error: true
  #     - name: Archive xcresult
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: xcresult-SparkCoreSnapshots
  #         path: xcresult-SparkCoreSnapshots.tar
  #         retention-days: 15

  build:
    needs: [core_build]
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "build_framework"
          target: "Spark"

  unit_tests:
    name: unit_tests
    needs: [build]
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "unit_tests"
          target: "Spark"
      - name: Tar files
        run: tar -cvf xcresult-Spark.tar out/Spark.xcresult
        continue-on-error: true
      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        with:
          name: xcresult-Spark
          path: xcresult-Spark.tar
          retention-days: 15
