name: build-framework
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  core_build:
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "build_framework"
          target: "SparkCore"

  # core_unit_tests:
  #   name: core_unit_tests
  #   needs: [core_build]
  #   runs-on: macos-13-xl
  #   env:
  #     target: SparkCore
  #   steps:
  #     - name: Checkout actions
  #       uses: actions/checkout@v4
  # - name: Run Sourcery
  #   uses: ./.github/composite-actions/sourcery
  # - name: Run Fastlane
  #   uses: ./.github/composite-actions/fastlane
  #   with:
  #     lane: "unit_tests"
  #     target: ${{ env.target }}
  # - name: Archive xcresult
  #   uses: ./.github/composite-actions/xcresult
  #   with:
  #     target: ${{ env.target }}

  core_snapshot_tests:
    name: core_snapshot_tests
    needs: [core_build]
    runs-on: macos-13-xl
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Get list of modified files
        id: get-modified-files
        run: |
          MODIFIED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})
          echo "modified_files=${MODIFIED_FILES}" >> $GITHUB_OUTPUT
      - name: Check if specified component folders are modified
        id: check-modified-components
        run: |
          if echo "${{ steps.get-modified-files.outputs.modified_files }}" | grep -E 'core/Sources/Components/' > /dev/null; then
              echo "Modified component folders."
              # Run core unit tests here
          else
              echo "No modifications in specified component folders. Skipping core unit tests."
          fi
      - name: Run Sourcery
        uses: ./.github/composite-actions/sourcery
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Run snapshots
        uses: actions/checkout@v4
        with:
          repository: adevinta/spark-ios-snapshots
          ref: ${{ env.branch }}
          path: spark-ios-snapshots
      - name: Run Fastlane
        uses: ./.github/composite-actions/fastlane
        with:
          lane: "unit_tests"
          target: "SparkDemo"
      - name: Archive xcresult
        uses: ./.github/composite-actions/xcresult
        with:
          target: "SparkCoreSnapshots"

  # build:
  #   needs: [core_build]
  #   runs-on: macos-13-xl
  #   steps:
  #     - name: Checkout actions
  #       uses: actions/checkout@v4
  #     - name: Run Fastlane
  #       uses: ./.github/composite-actions/fastlane
  #       with:
  #         lane: "build_framework"
  #         target: "Spark"

  # unit_tests:
  #   name: unit_tests
  #   needs: [build]
  #   runs-on: macos-13-xl
  #   env:
  #     target: Spark
  #   steps:
  #     - name: Checkout actions
  #       uses: actions/checkout@v4
  #     - name: Run Fastlane
  #       uses: ./.github/composite-actions/fastlane
  #       with:
  #         lane: "unit_tests"
  #         target: ${{ env.target }}
  #     - name: Archive xcresult
  #       uses: ./.github/composite-actions/xcresult
  #       with:
  #         target: ${{ env.target }}
